// This is the default/seed product catalog. The admin panel (see
// src/context/ProductsContext.jsx and src/admin/) lets you add, edit, and
// remove products from the browser without touching this file — those
// changes are saved separately and layered on top of this list. Editing
// here still works too (e.g. for a permanent change you want baked into
// every fresh visit); use the admin panel's "Reset" button to fall back to
// exactly what's below.
const products = [
  // ====== SNACKS (13) ======
  {
    id: 1,
    name: "Kumaoni Millet Crunch",
    category: "snacks",
    description: "Roasted finger millet with rock salt & cumin.",
    fullDescription:
      "From certified Kumaoni finger millet, slow-roasted with mustard oil.",
    ingredients: ["Finger Millet", "Rock Salt", "Mustard Oil", "Cumin"],
    weight: "200g",
    price: 180,
    shelfLife: "6 months",
    image: "/images/products.webp",
    badge: "Bestseller",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #F5E6D3, #E8D5B7)",
  },
  {
    id: 2,
    name: "Amaranth Chikki Bites",
    category: "snacks",
    description: "Crunchy amaranth & jaggery chikki, no sugar.",
    fullDescription:
      "Puffed amaranth bound with organic hill jaggery, loaded with almonds & sesame.",
    ingredients: ["Amaranth", "Jaggery", "Almonds", "Sesame", "Cardamom"],
    weight: "150g",
    price: 140,
    onSale: true,
    shelfLife: "4 months",
    image: "/images/products.webp",
    badge: "Healthy",
    badgeClass: "bg-s",
    bg: "linear-gradient(145deg, #EAF0CE, #D5E0A6)",
  },
  {
    id: 3,
    name: "Roasted Foxnut (Makhana)",
    category: "snacks",
    description: "Himalayan lotus seeds roasted in ghee.",
    fullDescription:
      "Premium foxnuts from North India, dry-roasted with a hint of pink salt & turmeric.",
    ingredients: ["Foxnut", "Ghee", "Pink Salt", "Turmeric"],
    weight: "100g",
    price: 190,
    shelfLife: "5 months",
    image: "/images/products.webp",
    badge: "Premium",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #FDE4C3, #F5D0A1)",
  },
  {
    id: 4,
    name: "Spicy Millet Noodle (Instant)",
    category: "snacks",
    description: "Ready-to-eat finger millet noodles.",
    fullDescription:
      "Steamed & dehydrated millet noodles with a spicy Himalayan spice mix.",
    ingredients: [
      "Finger Millet",
      "Whole Wheat",
      "Red Chilli",
      "Cumin",
      "Garlic",
    ],
    weight: "180g",
    price: 120,
    shelfLife: "8 months",
    image: "/images/products.webp",
    badge: "New",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #FADCD0, #F0C4B4)",
  },
  {
    id: 5,
    name: "Baked Ragi Chips",
    category: "snacks",
    description: "Crispy ragi chips with Himalayan herbs.",
    fullDescription:
      "Thinly rolled ragi dough, baked not fried, seasoned with rosemary & thyme.",
    ingredients: ["Ragi Flour", "Olive Oil", "Rosemary", "Thyme", "Rock Salt"],
    weight: "120g",
    price: 150,
    shelfLife: "4 months",
    image: "/images/products.webp",
    badge: "Baked",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #E2E8DD, #C9D4C2)",
  },
  {
    id: 6,
    name: "Pahadi Trail Mix",
    category: "snacks",
    description: "Raw nuts, seeds & dried berries from Kumaon.",
    fullDescription:
      "Almonds, walnuts, dried apricots, pumpkin seeds & wild barberries.",
    ingredients: ["Almonds", "Walnuts", "Apricot", "Pumpkin Seeds", "Barberry"],
    weight: "250g",
    price: 320,
    shelfLife: "6 months",
    image: "/images/products.webp",
    badge: "Energy",
    badgeClass: "bg-s",
    bg: "linear-gradient(145deg, #F3E8E0, #E4D3C5)",
  },
  {
    id: 7,
    name: "Sun-Dried Amla Candy",
    category: "snacks",
    description: "Raw amla sun-dried with black salt.",
    fullDescription:
      "Whole Himalayan amla sun-dried for 10 days, finished with black salt & turmeric.",
    ingredients: ["Amla", "Black Salt", "Turmeric", "Cumin"],
    weight: "200g",
    price: 130,
    shelfLife: "8 months",
    image: "/images/products.webp",
    badge: "Natural",
    badgeClass: "bg-s",
    bg: "linear-gradient(145deg, #DFF0D8, #C4E3B8)",
  },
  {
    id: 8,
    name: "Jhangora (Barnyard Millet) Puffs",
    category: "snacks",
    description: "Light & crunchy barnyard millet puffs.",
    fullDescription:
      "Puffed barnyard millet tossed with rock salt & lemon zest.",
    ingredients: ["Barnyard Millet", "Rock Salt", "Lemon Zest", "Mustard Oil"],
    weight: "100g",
    price: 110,
    shelfLife: "5 months",
    image: "/images/products.webp",
    badge: "Light",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #FFF3CC, #FFE399)",
  },
  {
    id: 9,
    name: "Garlic Millet Sticks",
    category: "snacks",
    description: "Savoury millet sticks with roasted garlic.",
    fullDescription:
      "Mixed millet flour sticks, oven-baked with garlic & fenugreek.",
    ingredients: ["Jowar", "Bajra", "Garlic", "Fenugreek", "Salt"],
    weight: "180g",
    price: 145,
    shelfLife: "4 months",
    image: "/images/products.webp",
    badge: "Savoury",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #FCEABB, #F6D385)",
  },
  {
    id: 10,
    name: "Moong Dal Khakri",
    category: "snacks",
    description: "Traditional moong dal crackers.",
    fullDescription:
      "Hand-pounded moong dal mixed with wheat flour, crispy fried in mustard oil.",
    ingredients: ["Moong Dal", "Wheat Flour", "Mustard Oil", "Turmeric"],
    weight: "200g",
    price: 160,
    shelfLife: "3 months",
    image: "/images/products.webp",
    badge: "Traditional",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #FAE3D9, #F5C7B3)",
  },
  {
    id: 11,
    name: "Mathri – Whole Wheat",
    category: "snacks",
    description: "Classic Pahadi mathri with carom seeds.",
    fullDescription:
      "Flaky whole wheat mathri with ajwain & black pepper, deep fried in pure ghee.",
    ingredients: ["Wheat Flour", "Ghee", "Ajwain", "Black Pepper"],
    weight: "250g",
    price: 200,
    shelfLife: "2 months",
    image: "/images/products.webp",
    badge: "Classic",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #F5E8C7, #E6D09E)",
  },
  {
    id: 12,
    name: "Pumpkin Seed Crunch",
    category: "snacks",
    description: "Roasted pumpkin seeds with Himalayan salt.",
    fullDescription:
      "Raw pumpkin seeds dry-roasted to perfection with pink salt.",
    ingredients: ["Pumpkin Seeds", "Pink Salt"],
    weight: "120g",
    price: 180,
    shelfLife: "5 months",
    image: "/images/products.webp",
    badge: "Vegan",
    badgeClass: "bg-s",
    bg: "linear-gradient(145deg, #E4F0D0, #CDE0AA)",
  },
  {
    id: 13,
    name: "Sattu Shake Mix",
    category: "snacks",
    description: "Instant roasted gram flour energy drink.",
    fullDescription:
      "Stone-ground roasted chana with cardamom & fennel, just add water.",
    ingredients: ["Roasted Gram", "Cardamom", "Fennel", "Rock Salt"],
    weight: "300g",
    price: 220,
    shelfLife: "4 months",
    image: "/images/products.webp",
    badge: "Instant",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #F0EBE1, #DED5C3)",
  },

  // ====== JUICES (8) ======
  {
    id: 14,
    name: "Wild Berry & Buransh Juice",
    category: "juices",
    description: "Rhododendron & wild berry blend, no sugar.",
    fullDescription: "Cold-pressed from Buransh flowers & forest berries.",
    ingredients: ["Buransh", "Wild Berries", "Lemon Zest"],
    weight: "500ml",
    price: 220,
    shelfLife: "4 months",
    image: "/images/products.webp",
    badge: "Seasonal",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #F3E1E8, #E3C4D3)",
  },
  {
    id: 15,
    name: "Pahadi Apple Juice",
    category: "juices",
    description: "Clear juice from Himalayan apples.",
    fullDescription:
      "Unfiltered juice from handpicked Kinnaur apples, no concentrate.",
    ingredients: ["Himalayan Apple"],
    weight: "500ml",
    price: 200,
    shelfLife: "3 months",
    image: "/images/products.webp",
    badge: "Pure",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #FCE1E1, #F5C4C4)",
  },
  {
    id: 16,
    name: "Amla Ginger Juice",
    category: "juices",
    description: "Immunity booster with amla & ginger.",
    fullDescription: "Raw amla & fresh ginger cold-pressed, no water added.",
    ingredients: ["Amla", "Ginger", "Lemon"],
    weight: "500ml",
    price: 240,
    onSale: true,
    shelfLife: "4 months",
    image: "/images/products.webp",
    badge: "Immunity",
    badgeClass: "bg-s",
    bg: "linear-gradient(145deg, #EBF3DF, #D5E8BF)",
  },
  {
    id: 17,
    name: "Kiwi Mint Cooler",
    category: "juices",
    description: "Tangy kiwi with fresh mint.",
    fullDescription: "Uttarakhand kiwis blended with mint leaves.",
    ingredients: ["Kiwi", "Mint", "Lemon"],
    weight: "500ml",
    price: 260,
    shelfLife: "3 months",
    image: "/images/products.webp",
    badge: "Tangy",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #E1F0E1, #C4E3C4)",
  },
  {
    id: 18,
    name: "Himalayan Lemonade",
    category: "juices",
    description: "Classic lemonade with pink salt.",
    fullDescription: "Freshly squeezed lemons with Himalayan pink salt & mint.",
    ingredients: ["Lemon", "Pink Salt", "Mint", "Water"],
    weight: "500ml",
    price: 180,
    shelfLife: "2 months",
    image: "/images/products.webp",
    badge: "Classic",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #FFF9D6, #FFEEA8)",
  },
  {
    id: 19,
    name: "Carrot & Beetroot Juice",
    category: "juices",
    description: "No added sugar, earthy & sweet.",
    fullDescription: "Locally grown carrots & beetroots, slow-juiced.",
    ingredients: ["Carrot", "Beetroot", "Ginger"],
    weight: "500ml",
    price: 210,
    shelfLife: "3 months",
    image: "/images/products.webp",
    badge: "Natural",
    badgeClass: "bg-s",
    bg: "linear-gradient(145deg, #FCE0D4, #F5BEA6)",
  },
  {
    id: 20,
    name: "Peach & Apricot Nectar",
    category: "juices",
    description: "Kumaoni peaches & wild apricots.",
    fullDescription: "Seasonal fruits from Ramgarh orchards, no preservatives.",
    ingredients: ["Peach", "Apricot", "Lemon"],
    weight: "500ml",
    price: 250,
    shelfLife: "3 months",
    image: "/images/products.webp",
    badge: "Seasonal",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #FCE8D5, #F5D0B5)",
  },
  {
    id: 21,
    name: "Mosambi Juice",
    category: "juices",
    description: "Sweet lime from the foothills.",
    fullDescription: "Fresh sweet lime, hand-squeezed, no machine.",
    ingredients: ["Sweet Lime"],
    weight: "500ml",
    price: 190,
    shelfLife: "2 months",
    image: "/images/products.webp",
    badge: "Fresh",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #F5F2D0, #E8E0A6)",
  },

  // ====== PICKLES (9) ======
  {
    id: 22,
    name: "Traditional Pahadi Achar",
    category: "pickles",
    description: "Mixed veggies in mustard oil.",
    fullDescription: "Badi, turnip, green chilli & seasonal veggies pickled.",
    ingredients: ["Badi", "Turnip", "Green Chilli", "Mustard Oil", "Turmeric"],
    weight: "400g",
    price: 160,
    shelfLife: "9 months",
    image: "/images/products.webp",
    badge: "Traditional",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #F3E9CD, #E4D3A1)",
  },
  {
    id: 23,
    name: "Garlic Achar",
    category: "pickles",
    description: "Whole garlic cloves in mustard oil.",
    fullDescription:
      "Sun-dried garlic cloves pickled with red chilli & fenugreek.",
    ingredients: [
      "Garlic",
      "Mustard Oil",
      "Red Chilli",
      "Fenugreek",
      "Turmeric",
    ],
    weight: "250g",
    price: 140,
    shelfLife: "8 months",
    image: "/images/products.webp",
    badge: "Pungent",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #F7E4D7, #EBC5AD)",
  },
  {
    id: 24,
    name: "Lemon Pickle",
    category: "pickles",
    description: "Sun-dried lemons with fenugreek.",
    fullDescription: "Whole lemons cut & sun-dried, mixed with salt & spices.",
    ingredients: ["Lemon", "Salt", "Turmeric", "Fenugreek", "Red Chilli"],
    weight: "250g",
    price: 120,
    onSale: true,
    shelfLife: "10 months",
    image: "/images/products.webp",
    badge: "Tangy",
    badgeClass: "bg-s",
    bg: "linear-gradient(145deg, #FFF0C2, #FFE085)",
  },
  {
    id: 25,
    name: "Mixed Vegetable Achar (Without Oil)",
    category: "pickles",
    description: "No-oil pickle with jaggery & spices.",
    fullDescription: "Carrot, radish, cauliflower in jaggery & mustard paste.",
    ingredients: [
      "Carrot",
      "Radish",
      "Cauliflower",
      "Jaggery",
      "Mustard",
      "Turmeric",
    ],
    weight: "300g",
    price: 150,
    shelfLife: "6 months",
    image: "/images/products.webp",
    badge: "No Oil",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #FCEAD2, #F5D2A6)",
  },
  {
    id: 26,
    name: "Green Chilli Pickle",
    category: "pickles",
    description: "Fiery whole green chillies.",
    fullDescription: "Handpicked green chillies with mustard, lime & salt.",
    ingredients: ["Green Chilli", "Mustard", "Lime", "Salt", "Turmeric"],
    weight: "200g",
    price: 100,
    shelfLife: "8 months",
    image: "/images/products.webp",
    badge: "Hot",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #E6F0D3, #CDE0A6)",
  },
  {
    id: 27,
    name: "Stuffed Red Chilli Pickle",
    category: "pickles",
    description: "Deseeded red chillies stuffed with spices.",
    fullDescription:
      "Mild red chillies filled with fennel, mustard & dry mango powder.",
    ingredients: ["Red Chilli", "Fennel", "Mustard", "Dry Mango", "Salt"],
    weight: "200g",
    price: 180,
    shelfLife: "10 months",
    image: "/images/products.webp",
    badge: "Special",
    badgeClass: "bg-s",
    bg: "linear-gradient(145deg, #FAD9D9, #F0BDBD)",
  },
  {
    id: 28,
    name: "Bamboo Shoot Pickle",
    category: "pickles",
    description: "Tender bamboo shoots in mustard oil.",
    fullDescription: "Young bamboo shoots boiled & pickled with local spices.",
    ingredients: [
      "Bamboo Shoot",
      "Mustard Oil",
      "Turmeric",
      "Chilli",
      "Garlic",
    ],
    weight: "250g",
    price: 190,
    shelfLife: "7 months",
    image: "/images/products.webp",
    badge: "Exotic",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #E1EAD8, #C5D6B8)",
  },
  {
    id: 29,
    name: "Jackfruit Pickle",
    category: "pickles",
    description: "Raw jackfruit with mustard & chilli.",
    fullDescription: "Tender raw jackfruit pieces sun-dried & pickled.",
    ingredients: ["Raw Jackfruit", "Mustard Oil", "Red Chilli", "Turmeric"],
    weight: "300g",
    price: 170,
    shelfLife: "6 months",
    image: "/images/products.webp",
    badge: "Unique",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #F8EBD4, #EED5A9)",
  },
  {
    id: 30,
    name: "Amla Pickle",
    category: "pickles",
    description: "Whole amla in mustard & fenugreek.",
    fullDescription: "Boiled amla with fennel, fenugreek & mustard oil.",
    ingredients: ["Amla", "Mustard Oil", "Fenugreek", "Fennel", "Turmeric"],
    weight: "250g",
    price: 145,
    shelfLife: "9 months",
    image: "/images/products.webp",
    badge: "Healthy",
    badgeClass: "bg-s",
    bg: "linear-gradient(145deg, #E9F0C7, #D3E09D)",
  },

  // ====== SWEETS (9) ======
  {
    id: 31,
    name: "Ragi & Amaranth Ladoo",
    category: "sweets",
    description: "No sugar, with jaggery & dry fruits.",
    fullDescription:
      "Stone-ground ragi, puffed amaranth, organic jaggery, almonds.",
    ingredients: ["Ragi Flour", "Amaranth", "Jaggery", "Almonds", "Cardamom"],
    weight: "250g",
    price: 200,
    shelfLife: "3 months",
    image: "/images/products.webp",
    badge: "No Sugar",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #F5E1D7, #E8C6B8)",
  },
  {
    id: 32,
    name: "Singori – Kumaoni Sweet",
    category: "sweets",
    description: "Sweet khoya wrapped in molu leaf.",
    fullDescription:
      "Traditional Kumaoni mithai made from thickened milk & sugar, wrapped in aromatic leaves.",
    ingredients: ["Khoya", "Sugar", "Molu Leaf", "Cardamom"],
    weight: "200g",
    price: 240,
    shelfLife: "5 days",
    image: "/images/products.webp",
    badge: "Perishable",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #FDF0DD, #F5DEB8)",
  },
  {
    id: 33,
    name: "Bal Mithai",
    category: "sweets",
    description: "Chocolate-like fudge coated with sugar balls.",
    fullDescription: "Roasted khoya fudge, a famous Almora sweet.",
    ingredients: ["Khoya", "Sugar", "Ghee"],
    weight: "200g",
    price: 220,
    onSale: true,
    shelfLife: "7 days",
    image: "/images/products.webp",
    badge: "Famous",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #F0E4D8, #E0CDBC)",
  },
  {
    id: 34,
    name: "Jhangora Kheer Mix",
    category: "sweets",
    description: "Barnyard millet kheer instant mix.",
    fullDescription:
      "Pre-cooked barnyard millet with dry fruits & cardamom, just add milk.",
    ingredients: ["Barnyard Millet", "Dry Fruits", "Cardamom", "Milk Powder"],
    weight: "200g",
    price: 180,
    shelfLife: "4 months",
    image: "/images/products.webp",
    badge: "Instant",
    badgeClass: "bg-s",
    bg: "linear-gradient(145deg, #EBE5F0, #D6CBE0)",
  },
  {
    id: 35,
    name: "Pumpkin Halwa",
    category: "sweets",
    description: "Traditional halwa made from pumpkin.",
    fullDescription: "Grated pumpkin slow-cooked in ghee & jaggery.",
    ingredients: ["Pumpkin", "Ghee", "Jaggery", "Cardamom", "Almonds"],
    weight: "300g",
    price: 210,
    shelfLife: "10 days",
    image: "/images/products.webp",
    badge: "Seasonal",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #FCE8D5, #F5D0AF)",
  },
  {
    id: 36,
    name: "Apple Cinnamon Energy Balls",
    category: "sweets",
    description: "No-bake apple & cinnamon bites.",
    fullDescription:
      "Dried apples, oats, cinnamon, peanut butter rolled in coconut.",
    ingredients: [
      "Dried Apple",
      "Oats",
      "Cinnamon",
      "Peanut Butter",
      "Coconut",
    ],
    weight: "150g",
    price: 250,
    shelfLife: "3 weeks",
    image: "/images/products.webp",
    badge: "Energy",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #FCE4E4, #F5C6C6)",
  },
  {
    id: 37,
    name: "Honey Sesame Ladoo",
    category: "sweets",
    description: "Sesame seeds & raw honey.",
    fullDescription:
      "Roasted sesame bound with raw Himalayan honey & cardamom.",
    ingredients: ["Sesame", "Raw Honey", "Cardamom"],
    weight: "200g",
    price: 190,
    shelfLife: "2 months",
    image: "/images/products.webp",
    badge: "Natural",
    badgeClass: "bg-s",
    bg: "linear-gradient(145deg, #FCF0C7, #F5E09E)",
  },
  {
    id: 38,
    name: "Khajur Roll",
    category: "sweets",
    description: "Dates stuffed with nuts & seeds.",
    fullDescription: "Medjool dates filled with almonds, coconut & chia seeds.",
    ingredients: ["Dates", "Almonds", "Coconut", "Chia Seeds"],
    weight: "200g",
    price: 280,
    shelfLife: "1 month",
    image: "/images/products.webp",
    badge: "Raw",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #F0E8DD, #E0D1BB)",
  },
  {
    id: 39,
    name: "Gulab Jamun (Baked)",
    category: "sweets",
    description: "Baked not fried, with sugar-free syrup.",
    fullDescription:
      "Soft milk balls baked & soaked in cardamom-infused honey syrup.",
    ingredients: ["Milk Powder", "Honey", "Cardamom", "Baking Powder"],
    weight: "250g",
    price: 230,
    shelfLife: "5 days",
    image: "/images/products.webp",
    badge: "Baked",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #F5DFE6, #E8C1CF)",
  },

  // ====== SUPERFOODS (6) ======
  {
    id: 40,
    name: "Raw Pahadi Honey",
    category: "superfoods",
    description: "Unprocessed wild honey, 1800m.",
    fullDescription:
      "Harvested from high-altitude Kumaon forest beehives, never heated.",
    ingredients: ["100% Raw Wild Honey"],
    weight: "300g",
    price: 350,
    shelfLife: "24 months",
    image: "/images/products.webp",
    badge: "Premium",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #FFF0B3, #FFE066)",
  },
  {
    id: 41,
    name: "Himalayan Rock Salt",
    category: "superfoods",
    description: "Pure pink rock salt, unrefined.",
    fullDescription: "Mined from ancient Himalayan deposits, rich in minerals.",
    ingredients: ["Himalayan Rock Salt"],
    weight: "500g",
    price: 120,
    onSale: true,
    shelfLife: "36 months",
    image: "/images/products.webp",
    badge: "Pure",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #FCE1E4, #F5C4CB)",
  },
  {
    id: 42,
    name: "Chyawanprash",
    category: "superfoods",
    description: "Traditional Ayurvedic jam with 40+ herbs.",
    fullDescription:
      "Amla base with ashwagandha, giloy, and other herbs, no preservatives.",
    ingredients: ["Amla", "Ashwagandha", "Giloy", "Ghee", "Honey"],
    weight: "500g",
    price: 450,
    shelfLife: "18 months",
    image: "/images/products.webp",
    badge: "Ayurvedic",
    badgeClass: "bg-s",
    bg: "linear-gradient(145deg, #E4EDD3, #CDDEB3)",
  },
  {
    id: 43,
    name: "Hemp Seeds",
    category: "superfoods",
    description: "Shelled hemp hearts, protein rich.",
    fullDescription: "Organic hemp seeds from Uttarakhand, cold-processed.",
    ingredients: ["Hemp Seeds"],
    weight: "200g",
    price: 320,
    shelfLife: "6 months",
    image: "/images/products.webp",
    badge: "Vegan",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #DCE6DF, #BCCFC0)",
  },
  {
    id: 44,
    name: "Rhododendron Powder",
    category: "superfoods",
    description: "Dried Buransh flower powder.",
    fullDescription:
      "Sun-dried rhododendron petals, used for making juice or chutney.",
    ingredients: ["Rhododendron Flowers"],
    weight: "100g",
    price: 280,
    shelfLife: "12 months",
    image: "/images/products.webp",
    badge: "Exotic",
    badgeClass: "bg-g",
    bg: "linear-gradient(145deg, #F5D6DF, #E8B5C4)",
  },
  {
    id: 45,
    name: "Wild Morel Mushroom",
    category: "superfoods",
    description: "Dried gucchi mushrooms.",
    fullDescription:
      "Handpicked morel mushrooms from high-altitude forests, sun-dried.",
    ingredients: ["Morel Mushroom"],
    weight: "25g",
    price: 600,
    shelfLife: "12 months",
    image: "/images/products.webp",
    badge: "Luxury",
    badgeClass: "bg-a",
    bg: "linear-gradient(145deg, #EAE6E1, #D3CAC1)",
  },
];

const testimonials = [
  {
    id: 1,
    rating: 5,
    text: "The Kumaoni Millet Crunch is now my everyday office snack. No guilt, amazing taste.",
    avatar: "👩",
    name: "Priya Sharma",
    location: "New Delhi",
  },
  {
    id: 2,
    rating: 5,
    text: "The Pahadi Achar brought back memories of my dadi's kitchen. WhatsApp ordering was super easy.",
    avatar: "👨",
    name: "Rahul Mehta",
    location: "Bengaluru",
  },
  {
    id: 3,
    rating: 5,
    text: "Raw Pahadi Honey is unlike anything in supermarkets — thick, aromatic, genuinely unprocessed.",
    avatar: "👩",
    name: "Anita Kapoor",
    location: "Mumbai",
  },
];

export { products, testimonials };
